version: "3"

services:

    wordpress:
        image: wordpress:php7.4-fpm-alpine
        restart: always
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: pppppu
            WORDPRESS_DB_PASSWORD: 123456
            WORDPRESS_DB_NAME: blog
        volumes:
            - wordpress:e:/docker_volumes/wordpress

    db:
        image: mariadb:10.5.1-bionic
        restart: always
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
            MYSQL_USER: pppppu
            MYSQL_PASSWORD: 123456
            MYSQL_DATABASE: blog
        volumes:
            - mariadb:e:/docker_volumes/mariadb
        ports:
            - 3306

volumes:
    wordpress:
    db:
